Repository itsmohit097/medi-hub, pull requests merged in 2024-06, with the labels that each got.

#235 Added a discord icon to the Readme me instead of link
  README.md
Labels: gssoc

#238 [Enhancement Styling]: Added a contributors section on homepage
  frontend/public/contrimage.png
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
  frontend/src/components/Contributors.css
  frontend/src/components/Contributors.jsx
  frontend/src/components/OurContributors.jsx
  frontend/src/import-export/ImportExport.js
Labels: level2, gssoc

#240 [Enhancement UI]: Added a FAQ section
  frontend/src/components/Faq.jsx
  frontend/src/import-export/ImportExport.js
  frontend/src/pages/Home.jsx
Labels: level2, gssoc

#244 [FEAT] : Adding a order page
  frontend/src/App.jsx
  frontend/src/components/CartPage.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/OrderedProduct.jsx
  frontend/src/components/ProductCard.jsx
  frontend/src/import-export/ImportExport.js
Labels: level3, gssoc

#256 [ENHANCEMENT STYLING] : Adding "Top Specialities" section on the homepage
  frontend/public/heart.png
  frontend/src/components/TopSpecialities.jsx
  frontend/src/import-export/ImportExport.js
  frontend/src/pages/Home.jsx
Labels: level2, gssoc

#262 [Enhancement Styling] : New Ui of login and signup page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lottie-animation/loginAnimation.json
  frontend/src/pages/Login.jsx
  frontend/src/pages/Signup.jsx
Labels: level3, gssoc
