Repository itsmohit097/medi-hub, pull requests merged in 2024-05, with the labels that each got.

#40 [FEAT]: Adding carousel in hero section
  frontend/package-lock.json
  frontend/package.json
  frontend/public/anton-8q-U8X1zkvI-unsplash.jpg
  frontend/public/pexels-fr3nks-287227.jpg
  frontend/public/pexels-fr3nks-305564.jpg
  frontend/public/pexels-karolina-grabowska-4021775.jpg
  frontend/public/pexels-pixabay-40568.jpg
  frontend/src/components/Hero.jsx
  frontend/src/index.css
Labels: level 1, ⭐ goal: addition, frontend, gssoc

#71 [Bug]: Sticky navbar on scrolling
  frontend/src/components/Navbar.jsx
Labels: bug, good first issue, level 1, frontend, gssoc

#95 feat: Added a GoToTop component
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/GoToTop.jsx
  frontend/src/index.css
Labels: level2, ⭐ goal: addition, frontend, gssoc

#89 [Fix]: Creating a navbar fixed at top
  frontend/src/components/Navbar.jsx
Labels: level1, frontend, 🌟 goal: UI design, goal: enhancement styling, gssoc

#118 [ENHANCEMENT STYLING]: Creating a navbar fixed at top
  frontend/src/components/Hero.jsx
Labels: good first issue, level1, goal: enhancement styling, gssoc

#129 [feat]: Adding 404 Error page
  frontend/public/404PageError.png
  frontend/src/App.jsx
  frontend/src/import-export/ImportExport.js
  frontend/src/pages/ErrorPage.jsx
Labels: level2, gssoc

#126 [Feat]: Adding online medicine feature and set up the payment integeration
  backend/app.js
  backend/src/controllers/UserCart.controller.js
  backend/src/controllers/medicine.controller.js
  backend/src/controllers/payment.controller.js
  backend/src/models/UserCart.model.js
  backend/src/models/medicine.model.js
  backend/src/models/payment.model.js
  backend/src/routes/UserCart.routes.js
  backend/src/routes/medicine.routes.js
  backend/src/routes/payment.routes.js
Labels: level3, backend, gssoc

#135 [FEAT]: Adding GitHub Automatic Greeting Bot
  .github/workflows/greetings.yaml
Labels: good first issue, level1, gssoc

#157 Add Password Hide and Show Eye , Password Strength Progress bar and strong password list.
  frontend/package-lock.json
  frontend/package.json
  frontend/public/hideEye.svg
  frontend/public/showEye.svg
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Signup.jsx
Labels: level2, gssoc

#167 Fix #146: Added a custom scrollbar
  frontend/src/index.css
Labels: level1, gssoc

#177 feat: add dropdown menu items (profile, appointments, wishlist, orde, logout on login button hover
  frontend/src/components/Navbar.jsx
Labels: level1, gssoc

#179 [ENHANCEMENT STYLING] Improve UI of the all doctors card
  frontend/src/components/Doctors.jsx
Labels: level1, gssoc

#181 Duplicate navbars removed
  frontend/src/pages/AllDoctors.jsx
Labels: level1, gssoc

#199 [Enhancement Functionality/Styling] : Making navbar responsive (hamburger menu) and fix the bug hover effect on login
  frontend/src/components/Navbar.jsx
Labels: level2, ⭐ goal: addition, gssoc
